2023-11-21 11_23_57,"Traceback (most recent call last):
  File ""C:\pywork\Project32\sec09\f_Exception.py"", line 14, in <module>
    f1(1.0, 0.0)
  File ""C:\pywork\Project32\sec09\f_Exception.py"", line 7, in f1
    return f2(a) + f2(b)
                   ^^^^^
  File ""C:\pywork\Project32\sec09\f_Exception.py"", line 10, in f2
    return 1.0 / x
           ~~~~^~~
ZeroDivisionError: float division by zero
"
